export const LOADING_REPOSITORIES = 'LOADING_REPOSITORIES';
export const REPOSOTORIES_FAILED = 'REPOSOTORIES_FAILED';
export const REPOSITORIES_COMPLETED = 'REPOSITORIES_COMPLETED';
export const CURRENT_REPOSITORY = 'CURRENT_REPOSITORY';
export const LOADING_COMMENTS = 'LOADING_COMMENTS';
export const COMMENTS_COMPLETED = 'COMMENTS_COMPLETED';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
